USE ROLE SYSADMIN;
USE SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCH_SF1;
USE WAREHOUSE XSMALL_WAREHOUSE;

-- Uncorrelated Scalar Subquery
SELECT 
    O_ORDERKEY, 
    O_TOTALPRICE
FROM 
    ORDERS
WHERE 
    O_TOTALPRICE > (SELECT APPROX_PERCENTILE(O_TOTALPRICE, 0.99) FROM ORDERS)
ORDER BY 
    O_TOTALPRICE DESC;

-- Uncorrelated Single Column / Multiple Row Subquery
SELECT 
    C_CUSTKEY, 
    C_NAME,
    C_NATIONKEY
FROM 
    CUSTOMER
WHERE 
    C_CUSTKEY IN (SELECT O_CUSTKEY FROM ORDERS ORDER BY O_TOTALPRICE DESC LIMIT 5);


-- ALL / ANY Subquery Operators
SELECT 
    C_CUSTKEY, C_NAME, C_NATIONKEY
FROM 
    CUSTOMER
WHERE 
    C_CUSTKEY = ALL (SELECT C_CUSTKEY FROM CUSTOMER LIMIT 5);

SELECT 
    C_CUSTKEY, C_NAME, C_NATIONKEY
FROM 
    CUSTOMER
WHERE 
    C_CUSTKEY = ANY (SELECT C_CUSTKEY FROM CUSTOMER LIMIT 5);

SELECT 
    C_CUSTKEY, C_NAME, C_NATIONKEY
FROM 
    CUSTOMER
WHERE 
    C_CUSTKEY <> ALL (SELECT O_CUSTKEY FROM ORDERS WHERE O_TOTALPRICE < 10000);

-- Uncorrelated Multiple Columns / Multiple Row Subquery
SELECT 
    C_CUSTKEY, C_NAME, C_NATIONKEY
FROM 
    (SELECT C_CUSTKEY, C_NAME, C_NATIONKEY FROM CUSTOMER LIMIT 10);

SELECT 
    C_CUSTKEY, C_NAME, C_NATIONKEY
FROM 
    (SELECT C_CUSTKEY AS CUSTOMER_KEY, C_NAME, C_NATIONKEY FROM CUSTOMER LIMIT 10);

-- Correlated Subqueries
SELECT
    O.O_ORDERKEY,
    O.O_ORDERDATE,
    O.O_TOTALPRICE
FROM
    ORDERS O
WHERE
    O.O_TOTALPRICE <= ( SELECT AVG(O_TOTALPRICE) FROM ORDERS WHERE O_ORDERDATE = O.O_ORDERDATE)
ORDER BY 
    O.O_ORDERDATE, O.O_TOTALPRICE;


-- EXISTS Subquery Operator
SELECT    
    *
FROM
    ORDERS
WHERE EXISTS (SELECT 1);

-- PARTS that have orders
SELECT 
    P_NAME
FROM 
    PART P
WHERE EXISTS (
   SELECT 1
   FROM LINEITEM LI
   WHERE LI.L_PARTKEY = P.P_PARTKEY);
