USE ROLE SYSADMIN;
USE SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCH_SF1;
USE WAREHOUSE XSMALL_WAREHOUSE;

-- One-to-many Relationship
SELECT 
    C_NAME, C_ADDRESS, O_ORDERDATE
FROM
    ORDERS
    INNER JOIN CUSTOMER ON C_CUSTKEY = O_CUSTKEY
ORDER BY 
    C_CUSTKEY;

-- Table Specification Order
SELECT 
    C_NAME, C_ADDRESS, O_ORDERDATE
FROM
    CUSTOMER
    JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
ORDER BY 
    C_CUSTKEY;

-- Identical Column Names
SELECT 
    C.C_NAME, C.C_ADDRESS, O.O_ORDERDATE
FROM
    ORDERS AS O
    JOIN CUSTOMER AS C ON C.C_CUSTKEY = O.O_CUSTKEY;

SELECT 
    C.C_NAME, C.C_ADDRESS, O.O_ORDERDATE
FROM
    ORDERS AS O
    JOIN CUSTOMER AS C ON (C.C_CUSTKEY = O.O_CUSTKEY);

SELECT 
    C.C_NAME, C.C_ADDRESS, O.O_ORDERDATE
FROM
    ORDERS AS O
    JOIN CUSTOMER AS C USING (C_CUSTKEY);

-- Join to table-like objects: views, table functions & subqueries

SELECT
  C.C_CUSTKEY,
  C.C_NAME,
  C.C_ADDRESS,
  O.O_ORDERKEY,
  O.O_ORDERDATE
FROM
  CUSTOMER C
INNER JOIN
  (
    SELECT
      O_ORDERKEY,
      O_CUSTKEY,
      O_ORDERDATE
    FROM
      ORDERS
    WHERE
      O_ORDERDATE >= '1995-01-01' AND O_ORDERDATE < '1996-01-01'
  ) O ON C.C_CUSTKEY = O.O_CUSTKEY;

-- Multi-table INNER join  

SELECT 
    C.C_NAME, C.C_ADDRESS, O.O_ORDERKEY, O.O_ORDERDATE, L.L_PARTKEY
FROM
    ORDERS O
    INNER JOIN CUSTOMER C ON (C.C_CUSTKEY = O.O_CUSTKEY)
    INNER JOIN LINEITEM L ON (O.O_ORDERKEY = L.L_ORDERKEY)
WHERE 
    C.C_NAME = 'Customer#000002903'
ORDER BY 
    O.O_ORDERDATE;