USE ROLE SYSADMIN;
USE SCHEMA DEMO_DB.DEMO_SCHEMA;
USE WAREHOUSE XSMALL_WAREHOUSE;

-- Repopulate EMPLOYEE table

INSERT OVERWRITE INTO EMPLOYEE 
VALUES 
    (1, 'Prakash', 'Das', '1987-01-02', 'IN'),
    (2, 'Madiha', 'Bradford', '1975-10-02', 'GB'),
    (3, 'James', 'Lines', '1999-09-20', 'GB'),
    (4, 'Amar', 'Krishnan', '2002-01-02', 'IN'), 
    (5, 'Inaaya', 'Andrews', '2001-01-02', 'US'), 
    (653, 'Randy', 'Caldwell', '1970-01-02', 'FI');

-- Single-row update

UPDATE EMPLOYEE 
SET EMP_ID = 6 
WHERE EMP_ID = 653;

SELECT * 
FROM EMPLOYEE
ORDER BY EMP_ID;

-- Multi-row update

UPDATE EMPLOYEE 
SET EMP_COUNTRY_CODE = 'IND' 
WHERE EMP_COUNTRY_CODE = 'IN';

UPDATE EMPLOYEE 
SET EMP_COUNTRY_CODE = 'FIN' 
WHERE EMP_COUNTRY_CODE = 'FI';

UPDATE EMPLOYEE 
SET EMP_COUNTRY_CODE = 'GBR' 
WHERE EMP_COUNTRY_CODE = 'GB';

UPDATE EMPLOYEE 
SET EMP_COUNTRY_CODE = 'USA' 
WHERE EMP_COUNTRY_CODE = 'US';

SELECT * 
FROM EMPLOYEE
ORDER BY EMP_ID;

-- FROM clause

CREATE TABLE ISO_COUNTRY_CODE (
    COUNTRY_CODE_ALPHA2 STRING(2),
    COUNTRY_CODE_ALPHA3 STRING(3), 
    COUNTRY_NAME STRING
);

INSERT INTO ISO_COUNTRY_CODE
VALUES 
  ('IN', 'IND', 'India'), 
  ('FI', 'FIN', 'Finland'), 
  ('GB', 'GBR', 'United Kingdom'), 
  ('US', 'USA', 'United States');

UPDATE EMPLOYEE 
SET EMP_COUNTRY_CODE = ISO_COUNTRY_CODE.COUNTRY_CODE_ALPHA2
FROM ISO_COUNTRY_CODE 
WHERE EMP_COUNTRY_CODE = ISO_COUNTRY_CODE.COUNTRY_CODE_ALPHA3;

SELECT * 
FROM EMPLOYEE
ORDER BY EMP_ID;

-- Reversed 

UPDATE EMPLOYEE 
SET EMP_COUNTRY_CODE = ISO_COUNTRY_CODE.COUNTRY_CODE_ALPHA3
FROM ISO_COUNTRY_CODE 
WHERE EMP_COUNTRY_CODE = ISO_COUNTRY_CODE.COUNTRY_CODE_ALPHA2;

SELECT * 
FROM EMPLOYEE
ORDER BY EMP_ID;