USE ROLE SYSADMIN;
USE SCHEMA DEMO_DB.DEMO_SCHEMA;
USE WAREHOUSE XSMALL_WAREHOUSE;

-- CSV File Format

CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY='"'
  DATE_FORMAT = 'dd/mm/yyyy';

-- Stage

CREATE STAGE MOVIE_STAGE
FILE_FORMAT = CSV_FILE_FORMAT;

-- Table

CREATE OR REPLACE TABLE MOVIE (
    MOVIE_ID STRING NOT NULL, 
    TITLE STRING,
    GENRE STRING, 
    DESCRIPTION STRING, 
    DIRECTOR_NAME STRING, 
    ACTORS STRING, 
    RELEASE_DATE DATE, 
    RUNTIME NUMBER(3,0),
    RATING NUMBER(3,1),
    GROSS NUMBER
);

-- Uploading a file to a stage with SnowSQL
-- PUT file:///Users/Admin/Downloads/imdb_movies.csv @MOVIE_STAGE AUTO_COMPRESS = FALSE;

LS @MOVIE_STAGE;

-- COPY INTO <table>

COPY INTO MOVIE FROM @MOVIE_STAGE;

-- Verify movie table

SELECT * FROM MOVIE;
