-- SQL OUTER JOIN Examples - Advanced Data Query Language (DQL)
-- This file demonstrates OUTER JOIN operations for handling unmatched data
-- OUTER JOINs are essential for finding missing relationships and complete data sets
-- ============================================
-- REQUIRED: This file uses the TPC-H database
-- Setup: duckdb data/tpc-h.db < examples/tpc-h.sql
-- Run with: duckdb data/tpc-h.db < exercises/section-6-dql-intermediate/outer-join.sql
-- ============================================

-- OUTER JOIN TYPES:
-- - LEFT OUTER JOIN (LEFT JOIN): Returns all rows from left table, matched rows from right
-- - RIGHT OUTER JOIN (RIGHT JOIN): Returns all rows from right table, matched rows from left
-- - FULL OUTER JOIN (FULL JOIN): Returns all rows from both tables, matched and unmatched
-- - CROSS JOIN: Returns Cartesian product (every row from left with every row from right)

-- OUTER JOIN SYNTAX:
-- SELECT columns FROM table1 LEFT [OUTER] JOIN table2 ON condition;      -- LEFT OUTER JOIN
-- SELECT columns FROM table1 RIGHT [OUTER] JOIN table2 ON condition;     -- RIGHT OUTER JOIN
-- SELECT columns FROM table1 FULL [OUTER] JOIN table2 ON condition;      -- FULL OUTER JOIN
-- SELECT columns FROM table1 CROSS JOIN table2;                          -- CROSS JOIN (no condition)

-- KEY CONCEPTS:
-- - NULL values appear for unmatched rows from the "outer" side
-- - Use IS NULL to find unmatched records
-- - Use IS NOT NULL to find matched records
-- - NULLS FIRST/LAST controls NULL ordering in ORDER BY

-- Example 1: LEFT OUTER JOIN - Find customers without orders
-- Question: "Which customers have not placed any orders?"
-- Returns all customers, with NULL for those without orders
SELECT c.c_custkey, c.c_name
FROM customer c
LEFT OUTER JOIN orders o ON c.c_custkey = o.o_custkey
WHERE o.o_orderkey IS NULL;

-- Example 2: RIGHT OUTER JOIN - Find orders without customers (data integrity check)
-- Question: "Which orders do not have a corresponding customer?"
-- This should typically return no results in a well-designed database
SELECT c.c_custkey, c.c_name, o.o_orderkey
FROM customer c
RIGHT OUTER JOIN orders o ON c.c_custkey = o.o_custkey
WHERE c.c_custkey IS NULL;

-- Example 3: FULL OUTER JOIN - Complete customer order summary
-- Question: "What is the total amount generated by each customer, including customers without orders?"
-- Returns all customers with their total order amounts, including 0 for customers without orders
SELECT c.c_custkey, SUM(o.o_totalprice) AS total_amount
FROM customer c
FULL OUTER JOIN orders o ON c.c_custkey = o.o_custkey
GROUP BY c.c_custkey
ORDER BY total_amount DESC NULLS LAST;

-- Example 4: CROSS JOIN - Cartesian product demonstration
-- Creates every possible combination of customers and nations
-- WARNING: Can produce very large result sets - use with caution
SELECT c.c_custkey, c.c_name, n.n_name
FROM customer c
CROSS JOIN nation n;