USE ROLE SYSADMIN;
USE SCHEMA DEMO_DB.DEMO_SCHEMA;
USE WAREHOUSE XSMALL_WAREHOUSE;

-- Virtual Warehouse

-- Metadata modifications
ALTER WAREHOUSE XSMALL_WAREHOUSE SET COMMENT = 'Modifying first extra small virtual warehouse.';

-- Behaviour modifications
ALTER WAREHOUSE XSMALL_WAREHOUSE SET WAREHOUSE_SIZE = 'SMALL';

ALTER WAREHOUSE XSMALL_WAREHOUSE RESUME;

ALTER WAREHOUSE XSMALL_WAREHOUSE SUSPEND;

ALTER WAREHOUSE IF EXISTS XSMALL_WAREHOUSE RENAME TO SMALL_WAREHOUSE;

USE WAREHOUSE SMALL_WAREHOUSE;


-- Database & Schema

ALTER DATABASE IF EXISTS DEMO_DB RENAME TO DEMO_DB_2;

USE DATABASE DEMO_DB_2;

ALTER SCHEMA IF EXISTS DEMO_SCHEMA RENAME TO DEMO_SCHEMA_2;

USE SCHEMA DEMO_SCHEMA_2;

ALTER DATABASE DEMO_DB_2 SET DATA_RETENTION_TIME_IN_DAYS = 10;

ALTER DATABASE DEMO_DB_2 UNSET DATA_RETENTION_TIME_IN_DAYS;


-- Table

ALTER TABLE EMPLOYEE ADD COLUMN EMP_ADDRESS STRING;

ALTER TABLE EMPLOYEE DROP COLUMN EMP_ADDRESS;

ALTER TABLE EMPLOYEE ALTER EMP_ID SET DATA TYPE NUMBER(10,0);

ALTER TABLE EMPLOYEE SET DATA_RETENTION_TIME_IN_DAYS = 10;

ALTER TABLE EMPLOYEE UNSET DATA_RETENTION_TIME_IN_DAYS;


-- Account & Session

USE ROLE ACCOUNTADMIN;

ALTER SESSION SET DATE_INPUT_FORMAT = 'DD/MM/YYYY';

ALTER ACCOUNT SET DATE_INPUT_FORMAT = 'DD/MM/YYYY';


-- Reset Configurations
ALTER WAREHOUSE IF EXISTS SMALL_WAREHOUSE RENAME TO XSMALL_WAREHOUSE;

USE WAREHOUSE XSMALL_WAREHOUSE;

ALTER WAREHOUSE XSMALL_WAREHOUSE SET COMMENT = 'My first extra small virtual warehouse.';

ALTER WAREHOUSE XSMALL_WAREHOUSE SET WAREHOUSE_SIZE = 'xsmall';

ALTER DATABASE DEMO_DB_2 RENAME TO DEMO_DB;

USE DATABASE DEMO_DB;

ALTER SCHEMA DEMO_SCHEMA_2 RENAME TO DEMO_SCHEMA;

USE SCHEMA DEMO_SCHEMA;

ALTER TABLE EMPLOYEE ALTER EMP_ID SET DATA TYPE NUMERIC;
