USE ROLE SYSADMIN;
USE SCHEMA DEMO_DB.DEMO_SCHEMA;
USE WAREHOUSE XSMALL_WAREHOUSE;

-- GROUP BY
SELECT 
    GENRE, COUNT(MOVIE_ID) AS MOVIE_COUNT
FROM
    MOVIE
GROUP BY 
    GENRE
ORDER BY 
    MOVIE_COUNT DESC;

-- Aggregate functions: MAX, MIN, AVG, COUNT, SUM
SELECT 
    DIRECTOR_NAME,
    COUNT(GROSS),
    MAX(GROSS),
    MIN(GROSS),
    AVG(GROSS),
    SUM(GROSS)
FROM
    MOVIE
GROUP BY 
    DIRECTOR_NAME
LIMIT 
    1;

SELECT 
    TITLE, DIRECTOR_NAME, GENRE, GROSS
FROM
    MOVIE
WHERE 
    DIRECTOR_NAME = 'James Gunn'
ORDER BY 
    GROSS;

-- Grouping on multiple columns 
SELECT 
    GENRE,
    YEAR(RELEASE_DATE),
    COUNT(MOVIE_ID) AS MOVIE_COUNT
FROM
    MOVIE
GROUP BY 
    GENRE, YEAR(RELEASE_DATE)
ORDER BY 
    GENRE, YEAR(RELEASE_DATE);

SELECT 
    GENRE,
    YEAR(RELEASE_DATE),
    COUNT(MOVIE_ID) AS MOVIE_COUNT
FROM
    MOVIE
GROUP BY 
    1, 2
ORDER BY 
    1, 2;

-- Roll up
SELECT 
    YEAR(RELEASE_DATE),
    GENRE,
    SUM(GROSS)
FROM
    MOVIE
GROUP BY 
    YEAR(RELEASE_DATE), GENRE
ORDER BY
    YEAR(RELEASE_DATE), GENRE; 

SELECT 
    YEAR(RELEASE_DATE),
    GENRE,
    SUM(GROSS)
FROM
    MOVIE
GROUP BY 
    ROLLUP (YEAR(RELEASE_DATE), GENRE)
ORDER BY
    YEAR(RELEASE_DATE), GENRE; 
