USE ROLE SYSADMIN;
USE SCHEMA DEMO_DB.DEMO_SCHEMA;
USE WAREHOUSE XSMALL_WAREHOUSE;


-- GROUP BY WHERE
SELECT 
    DIRECTOR_NAME, 
    AVG(RATING) AS AVG_RATING
FROM
    MOVIE
WHERE
    RATING >= 8
GROUP BY
    DIRECTOR_NAME
ORDER BY
    AVG_RATING DESC;

-- GROUP BY HAVING
SELECT 
    DIRECTOR_NAME, 
    AVG(RATING) AS AVG_RATING
FROM
    MOVIE
GROUP BY
    DIRECTOR_NAME
HAVING 
    AVG_RATING >= 8
ORDER BY 
    AVG_RATING DESC;

SELECT 
    DIRECTOR_NAME, 
    SUM(GROSS) AS TOTAL_GROSS
FROM 
    MOVIE
WHERE 
    GENRE = 'Action'
GROUP BY 
    DIRECTOR_NAME
HAVING 
    SUM(GROSS) > 1000
ORDER BY 
    TOTAL_GROSS DESC;
