USE ROLE SYSADMIN;
USE SCHEMA UK_ROWLEVEL_TRANSACTION_DATA__SAMPLE.PUBLIC_LISTING;
USE WAREHOUSE XSMALL_WAREHOUSE;

// Analyse Transaction Value And Volume By User
/*
How does user volume and value of purchases change by month? 
*/
WITH AGG_BY_USER AS 
(
SELECT YEAR(TRANSACTION_DATE) AS YEAR,
	   MONTH(TRANSACTION_DATE) AS MONTH,
       USER_REFERENCE,
       COUNT(*)   AS COUNT,
       SUM(AMOUNT) AS SPEND
FROM PUBLIC_LISTING.TRANSACTIONS
WHERE CREDIT_DEBIT = 'Debit'
GROUP BY YEAR, MONTH, USER_REFERENCE
)
SELECT YEAR,
			 MONTH,
       AVG(COUNT) AS AVERAGE_TRANSACTIONS,
       AVG(SPEND) AS AVERAGE_SPEND
FROM AGG_BY_USER
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;

-- Derived Table (Subquery)
SELECT 
    YEAR,
    MONTH,
    AVG(COUNT) AS AVERAGE_TRANSACTIONS,
    AVG(SPEND) AS AVERAGE_SPEND
FROM 
    (
        SELECT 
            YEAR(TRANSACTION_DATE) AS YEAR,
            MONTH(TRANSACTION_DATE) AS MONTH,
            USER_REFERENCE,
            COUNT(*) AS COUNT,
            SUM(AMOUNT) AS SPEND
        FROM 
            PUBLIC_LISTING.TRANSACTIONS
        WHERE 
            CREDIT_DEBIT = 'Debit'
        GROUP BY 
            YEAR, MONTH, USER_REFERENCE
    ) AS AGG_BY_USER
GROUP BY 
    YEAR, MONTH
ORDER BY 
    YEAR, MONTH;


// Understand Typical Purchase Volume And Value At Specific Merchants
/*
What is the average value and volume of transactions per user by month for Tesco and Sainsbury’s customers?
*/
WITH AGG_BY_USER AS 
(
SELECT YEAR(TRANSACTION_DATE) AS YEAR,
       MONTH(TRANSACTION_DATE) AS MONTH,
       MERCHANT_BUSINESS_LINE,
       USER_REFERENCE,
       COUNT(*)   AS COUNT,
			 SUM(AMOUNT) AS SPEND
FROM PUBLIC_LISTING.TRANSACTIONS
WHERE CREDIT_DEBIT = 'Debit'
AND MERCHANT_BUSINESS_LINE IN ('Tesco Supermarket', 'Sainsburys Supermarket')
GROUP BY YEAR, MONTH, MERCHANT_BUSINESS_LINE, USER_REFERENCE
)
SELECT YEAR,
       MONTH,
       MERCHANT_BUSINESS_LINE AS SUPERMARKET,
       AVG(COUNT) AS AVERAGE_TRANSACTIONS,
       AVG(SPEND) AS AVERAGE_SPEND
FROM AGG_BY_USER
GROUP BY YEAR, MONTH, SUPERMARKET
ORDER BY YEAR, MONTH, SUPERMARKET DESC;

// Competitive Benchmarking By Spend Category
/*
What were the most popular fashion retailers by year across each age band? 
*/
WITH TOTAL_TRANSACTIONS_BY_MERCHANT AS 
(
SELECT YEAR(TRANSACTION_DATE) AS YEAR,
       AGE_BAND,
       MERCHANT_BUSINESS_LINE,
       SUM(AMOUNT) AS TOTAL_SPEND
FROM PUBLIC_LISTING.TRANSACTIONS
WHERE CREDIT_DEBIT = 'Debit'
AND AUTO_PURPOSE_TAG_NAME LIKE '%Clothes%'
GROUP BY YEAR, AGE_BAND, MERCHANT_BUSINESS_LINE
)
SELECT DISTINCT YEAR,
       AGE_BAND,
       FIRST_VALUE(MERCHANT_BUSINESS_LINE) OVER (PARTITION BY YEAR, AGE_BAND ORDER BY TOTAL_SPEND DESC) AS TOP_RETAILER
FROM TOTAL_TRANSACTIONS_BY_MERCHANT
ORDER BY YEAR, AGE_BAND;

