USE ROLE SYSADMIN;
USE SCHEMA DEMO_DB.DEMO_SCHEMA;
USE WAREHOUSE XSMALL_WAREHOUSE;

-- Transactions

START TRANSACTION NAME MY_FIRST_TRANSACTION;

SHOW TRANSACTIONS;

BEGIN TRANSACTION;

SHOW TRANSACTIONS;

-- DDL: CREATE TABLE
-- DML: INSERT INTO
-- DQL: SELECT * FROM

UPDATE EMPLOYEE SET EMP_FIRST_NAME = 'Amir' WHERE EMP_ID = 4;

INSERT INTO EMPLOYEE VALUES (8, 'Sophia', 'Johnson', '1995-05-15', 'CA');

INSERT INTO EMPLOYEE VALUES (9, 'Liam', 'Brown', '1983-11-20', 'AU');


SELECT * FROM EMPLOYEE;

COMMIT;

SHOW TRANSACTIONS;

SELECT * FROM EMPLOYEE;

BEGIN TRANSACTION;

INSERT INTO EMPLOYEE VALUES (10, 'Jose', 'García', '1991-03-03', 'US/');

INSERT INTO EMPLOYEE VALUES (11, 'Valeria', 'Alonso', '1981-07-03', 'US/');

SELECT * FROM EMPLOYEE;

ROLLBACK;


-- Implicit Transaction actions

START TRANSACTION NAME MY_THIRD_TRANSACTION;

INSERT INTO EMPLOYEE VALUES (10, 'Alisha', 'Uppal', '1981-09-03', 'IN/');

SHOW TRANSACTIONS;

ALTER TABLE EMPLOYEE SET COMMENT = 'A table which contains information about employees in an organisation.';

SHOW TRANSACTIONS;

SELECT * FROM EMPLOYEE;

-- AUTOCOMMIT

ALTER SESSION SET AUTOCOMMIT = FALSE;

INSERT INTO EMPLOYEE VALUES (12, 'James', 'Andrews', '2010-01-02', 'GB');

SHOW TRANSACTIONS;
    
INSERT INTO EMPLOYEE VALUES (13, 'Luke', 'Smith', '1990-01-10', 'GB');

SELECT * FROM EMPLOYEE;

COMMIT;
